# Generated by Django 4.0.4 on 2022-05-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contactos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='id',
        ),
        migrations.AlterField(
            model_name='contacto',
            name='cedula',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
